PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX y: <http://mpii.de/yago/resource/>

SELECT ?x 
WHERE { 
	?x y:livesIn <http://mpii.de/yago/resource/Athens> . 
}
