PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX ub: <http://swat.cse.lehigh.edu/onto/univ-bench.owl#>
SELECT ?x ?y ?z 
WHERE { 
	?z ub:subOrganizationOf ?y . 
	?y rdf:type ub:University . 
	?z rdf:type ub:Department . 
	?x ub:memberOf ?z . ?x rdf:type ub:GraduateStudent . 
	?x ub:undergraduateDegreeFrom ?y . 
}
